### PR TITLE
Better tests for finalsize

### LINKED ISSUE #29: Check for r0 > 1
`final_size` returns final epidemic sizes of 0.0 for any `prop_initial_infected` (> 0.0) when `r0` < 1.0. This is implausible as some individuals are already initially infected. The algorithm implemented here (most likely) does not work for `r0` < 1.0, and `final_size` should stop when `r0` < 1.0 is provided.

### LINKED ISSUE #30: Check for plausible epidemic final size
Check that `final_size` returns a vector with values in the range `prop_initial_infected` and 1.0 for `r0` > 1.0.

### LINKED ISSUE #31: Allow passing single prop_suscep value
Allow users to specify a single `prop_suscep` for all age groups.

### PR DESCRIPTION
**Pull request by pratikunterwegs**
Adding better tests for `finalsize` and `final_size`.
- Fixes #29 by setting lower limit for `r0` at 1.0. Values below this result in a final epidemic size of 0.0.
- Fixes #30 by checking that epidemic final sizes are below `prop_initial_infected` and 1.0 _in each age group_
- Adds tests by @BlackEdder taken from #26 for plausible epidemic sizes
- Adds the helper function `upper_limit` from @BlackEdder from #26 
- Fixes #31 by allow `prop_suscep` to be a single population wide value

### CODE REVIEW

**Comment by pratikunterwegs** [comment]
Hi @Bisaloo and @thibautjombart, just wanted to check whether we have a policy on helper functions such as https://github.com/epiverse-trace/finalsize/pull/32/commits/f7f8eccc2fba8e33478163abf5c728e70d87f7c6? An internal function perhaps? Or would it be better as an exported function?

File: R/final_size.R [hunk 1]
```diff
@@ -47,12 +47,22 @@ final_size <- function(r0 = 2, contact_matrix, demography_vector,
...
   if (is.null(prop_suscep)) {
     prop_suscep <- rep(1, length(demography_vector))
-  } # Assume fully susceptible if no entry
+  } else {
+    checkmate::assert_numeric(
+      prop_suscep,
+      lower = 0.0, upper = 1.0, finite = TRUE
+    )
+    if (length(prop_suscep) == 1L) {
+      prop_suscep <- rep(prop_suscep, length(demography_vector))
```
Comment (Bisaloo) [inline R/final_size.R:56]: Another, simpler(?) way to deal with #31 is to allow `prop_suscep` to be of length 1 in L71-74. It will then be automatically recycled.

I like it better because it doesn't burden the function with more default settings and recycling elements of length 1 is very idiomatic in R anyways so I don't think it hurts readability. The mere fact that we're considering adding this behaviour is a proof of that.

Open to discussion on this though.

**Review by Bisaloo — COMMENTED** [review]
Other possible tests. Feel free to convert into an issue if you want to keep this PR short:

- no bleeding of infections from one age group to the other if the contact rate is set to 0
- higher values of R0 result in higher finalsizes (all else being constant)
- finalsize cannot exceed prop_suscep

I'll let the epidemiologists confirm that these tests make sense

File: R/final_size.R (hunk 1 above)
Comment (pratikunterwegs) [reply R/final_size.R]: I've updated the asserts around `prop_suscep` to suit.

>     * no bleeding of infections from one age group to the other if the contact rate is set to 0

Is referenced in #33

>     * higher values of R0 result in higher finalsizes (all else being constant)

Already tested

>     * finalsize cannot exceed prop_suscep

This is a bit tricky, because I'm not sure that `prop_suscep` is actually the proportion susceptible - maybe the epidemiologists could weigh in on how this test should be structured?

File: R/final_size.R [hunk 2]
```diff
@@ -44,24 +44,34 @@ final_size <- function(r0 = 2, contact_matrix, demography_vector,
...
+  } else {
+    checkmate::assert_numeric(
+      prop_suscep,
+      lower = 0.0, upper = 1.0, finite = TRUE
+    )
+    if (length(prop_suscep) > 1L) {
+      assertthat::assert_that(
+        length(demography_vector) == length(prop_suscep),
+        msg = "demography vector needs to be same size as susceptibility vector"
+      )
```
Comment (thibautjombart) [inline R/final_size.R:59]: Relating to the conversation on minimizing dependencies, I would either use base R or checkmate here.

File: R/final_size.R [hunk 3]
```diff
@@ -44,24 +44,34 @@ final_size <- function(r0 = 2, contact_matrix, demography_vector,
...
+  checkmate::assert_number(r0, lower = 1.0, finite = TRUE)
+  checkmate::assert_numeric(demography_vector, lower = 0.0)
   checkmate::assert_matrix(contact_matrix)
-  checkmate::assert_numeric(prop_initial_infected)
+  checkmate::assert_numeric(prop_initial_infected, lower = 0.0, upper = 1.0)
 
   assertthat::assert_that(
     nrow(contact_matrix) == length(demography_vector),
     msg = "demography vector needs to be same size as contact matrix"
   )
```
Comment (thibautjombart) [inline R/final_size.R:74]: Same comment as before: I would use base R here or checkmate.

**Review by thibautjombart — COMMENTED** [review]
Thanks for this! 

In line with the conversation on dependencies, I flagged it may be best using base R or checkmate instead as assertthat? But feel free to differ this change to a later PR if you want to get this one through.

File: R/final_size.R (hunk 2 above)
Comment (pratikunterwegs) [reply R/final_size.R]: Removed in https://github.com/epiverse-trace/finalsize/pull/32/commits/66ad999a44cb9e558d5f7b36d12d4018e15b0127, https://github.com/epiverse-trace/finalsize/pull/32/commits/387dc6d201238a87d0953fdb1cf34f16d8ccf8d4

File: R/final_size.R (hunk 3 above)
Comment (pratikunterwegs) [reply R/final_size.R]: Removed in https://github.com/epiverse-trace/finalsize/pull/32/commits/66ad999a44cb9e558d5f7b36d12d4018e15b0127, https://github.com/epiverse-trace/finalsize/pull/32/commits/387dc6d201238a87d0953fdb1cf34f16d8ccf8d4

**Review by thibautjombart — APPROVED** [review]
